const activities = [
  { id: "lecture", icon: "🏫", name: "Kuliah", detail: "Hadiri kelas", impact: "+ akademik", energy: -12, academic: 8, free: -8, hunger: -10, text: "Kehadiranmu tercatat! Satu langkah kecil untuk memahami materi." },
  { id: "assignment", icon: "📝", name: "Kerjakan tugas", detail: "Kejar deadline", impact: "+ akademik", energy: -18, academic: 14, free: -15, hunger: -8, text: "Tugas selesai lebih awal. Beban pikiranmu juga ikut berkurang." },
  { id: "study", icon: "📚", name: "Belajar mandiri", detail: "Review materi", impact: "+ akademik", energy: -15, academic: 12, free: -12, hunger: -8, text: "Materi makin menempel. Kamu sedang membangun fondasi nilai yang bagus." },
  { id: "rest", icon: "😴", name: "Istirahat", detail: "Recharge energi", impact: "+ energi", energy: 20, academic: -2, free: 8, hunger: -4, text: "Baterai tubuh terisi! Istirahat bukan kemunduran, ini strategi." },
  { id: "meal", icon: "🍜", name: "Makan bergizi", detail: "Isi tenaga", impact: "+ kenyang", energy: 8, academic: 1, free: -3, hunger: 25, text: "Perut bahagia, otak siap diajak berpikir. Jangan lupa minum air juga!" },
  { id: "club", icon: "🎤", name: "Organisasi", detail: "Temui teman", impact: "+ relasi", energy: -14, academic: 3, free: -10, hunger: -9, text: "Relasi dan pengalamanmu bertambah. Kampus bukan cuma soal buku." },
];
const days = ["Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu"];
const dayTitles = ["Start yang cerah", "Tugas mulai berdatangan", "Pertengahan minggu", "Tetap fokus, ya!", "Finish line terlihat", "Waktu untuk berkembang", "Hari terakhir yang santai"];
const state = { day: 0, slots: 0, energy: 78, academic: 50, free: 65, hunger: 80, chosen: [] };
const $ = (id) => document.getElementById(id);
const elements = { day: $("dayValue"), dayTitle: $("dayTitle"), slotCount: $("slotCount"), chosen: $("chosenList"), activity: $("activityGrid"), feedback: $("dayFeedback"), next: $("nextDayBtn"), energy: $("energyValue"), academic: $("academicValue"), free: $("freeValue"), hunger: $("hungerValue"), energyBar: $("energyBar"), academicBar: $("academicBar"), freeBar: $("freeBar"), hungerBar: $("hungerBar"), dots: $("dayDots"), modal: $("resultModal") };

function clamp(value) { return Math.max(0, Math.min(100, value)); }
function renderDays() { elements.dots.innerHTML = days.map((_, index) => `<i class="day-dot ${index < state.day ? "done" : index === state.day ? "active" : ""}"></i>`).join(""); }
function renderStats() { const stats = [["energy", state.energy], ["academic", state.academic], ["free", state.free], ["hunger", state.hunger]]; stats.forEach(([name, value]) => { elements[name].textContent = name === "academic" ? value : `${value}%`; elements[`${name}Bar`].style.width = `${value}%`; }); elements.day.textContent = state.day + 1; renderDays(); }
function renderActivities() { elements.activity.innerHTML = activities.map((item, index) => `<button class="activity-btn" type="button" data-index="${index}" ${state.slots >= 3 ? "disabled" : ""}><span class="activity-emoji">${item.icon}</span><strong>${item.name}</strong><small>${item.detail}</small><span class="impact">${item.impact}</span></button>`).join(""); elements.activity.querySelectorAll("button").forEach((button) => button.addEventListener("click", () => chooseActivity(Number(button.dataset.index)))); }
function renderSchedule() { if (!state.chosen.length) { elements.chosen.innerHTML = '<div class="empty-slot">Pilih kegiatan untuk mengisi jadwalmu <span>↓</span></div>'; return; } elements.chosen.innerHTML = state.chosen.map((item, index) => `<div class="chosen-slot"><span class="slot-emoji">${item.icon}</span><span>${["Pagi", "Siang", "Sore"][index]}: ${item.name}</span></div>`).join(""); }
function renderDay() { elements.dayTitle.textContent = `${days[state.day]}: ${dayTitles[state.day]}`; elements.slotCount.textContent = `${state.slots} / 3 slot`; renderStats(); renderActivities(); renderSchedule(); elements.feedback.hidden = true; elements.next.hidden = true; }
function chooseActivity(index) { const item = activities[index]; state.slots += 1; state.chosen.push(item); state.energy = clamp(state.energy + item.energy); state.academic = clamp(state.academic + item.academic); state.free = clamp(state.free + item.free); state.hunger = clamp(state.hunger + item.hunger); elements.slotCount.textContent = `${state.slots} / 3 slot`; renderStats(); renderSchedule(); renderActivities(); if (state.slots === 3) endDay(); }
function endDay() { const exhausted = state.energy < 25; const hungry = state.hunger < 25; elements.feedback.className = exhausted || hungry ? "day-feedback warning" : "day-feedback"; elements.feedback.innerHTML = exhausted ? "⚠️ <strong>Hari yang berat.</strong> Energimu menipis. Besok sempatkan istirahat agar tidak burnout." : hungry ? "🍽️ <strong>Perutmu protes.</strong> Jadwal padat boleh, tetapi makan tetap prioritas." : "✅ <strong>Jadwal selesai!</strong> Kamu berhasil melewati hari ini dengan cukup seimbang."; elements.feedback.hidden = false; elements.next.hidden = false; elements.next.textContent = state.day === 6 ? "Lihat hasil minggu ini" : `Lanjut ke ${days[state.day + 1]}`; }
function nextDay() { if (state.day === 6) { showResult(); return; } state.day += 1; state.slots = 0; state.chosen = []; renderDay(); }
function showResult() { const balance = state.energy >= 45 && state.academic >= 75 && state.free >= 35 && state.hunger >= 40; const great = state.energy >= 60 && state.academic >= 90 && state.free >= 40 && state.hunger >= 50; $("finalAcademic").textContent = state.academic; $("finalEnergy").textContent = `${state.energy}%`; $("finalFree").textContent = `${state.free}%`; $("resultTitle").textContent = great ? "Kamu mahasiswa teladan!" : balance ? "Minggumu cukup seimbang!" : "Minggu yang penuh pelajaran!"; $("resultMessage").textContent = great ? "Nilai aman, energi terjaga, dan hidup sosialmu tetap jalan. Strategi waktumu keren!" : balance ? "Kamu berhasil menjaga banyak hal tetap berjalan. Sedikit penyesuaian bisa membuat minggu depan lebih nyaman." : "Tidak apa-apa. Sekarang kamu tahu kapan harus belajar, istirahat, makan, dan meminta bantuan."; $("verdictText").textContent = great ? "🏆 Predikat: Campus Legend" : balance ? "🌟 Predikat: Survivor Seimbang" : "🌱 Predikat: Masih Bertumbuh"; elements.modal.hidden = false; }
function reset() { state.day = 0; state.slots = 0; state.energy = 78; state.academic = 50; state.free = 65; state.hunger = 80; state.chosen = []; elements.modal.hidden = true; renderDay(); }
elements.next.addEventListener("click", nextDay); $("restartBtn").addEventListener("click", reset); $("playAgainBtn").addEventListener("click", reset); renderDay();